name: Tests
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Run linter and package audit
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn -v
          python -V
          yarn

      - name: Lint
        run: yarn run lint

      - name: Audit Production Dependencies
        run: yarn audit --groups dependencies || true

  test:
    runs-on: ubuntu-20.04
    name: Run tests
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn -v
          python -V
          yarn

      - name: Test
        run: |
          yarn build
          yarn run test
